services:
  postgres:
    image: postgres:16-alpine
    container_name: pms_hotelero_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: pms_pass
      POSTGRES_DB: pms_hotelero
    ports:
      - "5432:5432"
    volumes:
      - pms_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pms_user -d pms_hotelero"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pms_pg_data:
